CREATE DATABASE IF NOT EXISTS `light_control`;

CREATE TABLE IF NOT EXISTS `Configs` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Key` VARCHAR(255) NOT NULL,
    `Value` BOOLEAN NOT NULL,
    `Created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`, `Key`)
);

CREATE TABLE IF NOT EXISTS `Roles` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`Label` varchar(50) NOT NULL,
	`Description` varchar(255) NOT NULL,
	`Created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`, `Label`)
);

CREATE TABLE IF NOT EXISTS Users (
	`ID` int NOT NULL AUTO_INCREMENT,
	`UserName` varchar(50) NOT NULL,
    `PassWord_Encrypted` varchar(255) NOT NULL,
    `RoleID` INT NOT NULL,
	`Created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`, `UserName`),
    FOREIGN KEY (`RoleID`) REFERENCES `Roles`(`ID`)
);

CREATE TABLE IF NOT EXISTS `Lights` (
	`ID` INT NOT NULL AUTO_INCREMENT,
    `Key` VARCHAR(100) NOT NULL, 
    `RGB` BOOLEAN NOT NULL,
    `Color` VARCHAR(7) NOT NULL,
    `Dimmable` BOOLEAN NOT NULL,
    `Luminosity` INT NOT NULL,
    `Created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (`ID`, `Key`)
);